### ISSUE TITLE
Readme get/put example potentially missing state_dir parameter

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/bbl-state-resource#4]
We have a pipeline with the following jobs that follow the example in the readme (https://github.com/cloudfoundry/bbl-state-resource/blob/a02832129633047f08ab1f6ac6d53ee66530c41c/README.md#examples):

```
jobs:
- name: bbl-up
  plan:
  - get: bbl-state
  - put: bbl-state
    params:
      command: up
      name_file: bbl-state/name
```

When configured like this, we get the error: `failed to create /tmp/build/put/bbl-state directory: mkdir /tmp/build/put/bbl-state: file exists`

When we add `state_dir: bbl-state` to the `params` section, our `bbl up` works fine

Should this additional parameter be added to the example in the readme? Are we misconfiguring something and does it work without it?

**Comment by cwlbraa** [comment]
this is an interesting name collision problem -- I think this only happens because you (and the example!) named your particular resource `bbl-state`, which also happens to be the default directory for downloading the state that a "put" uses. Could you verify by naming it something else? We have slightly modified versions of those pipelines in our pipelines in [our ci](https://infra.ci.cf-app.com/teams/main/pipelines/bosh-bootloader?groups=bbl-state-resource) that don't explode with that particular error.

However, this is definitely a bug.

Thinking out loud: The first way out of this is to use the `put/bbl-state/` directory as a state dir if it's found. The problem there is that
```
jobs:
- name: bbl-up
  plan:
  - get: bbl-state
  - put: a-second-bbl-state
    params:
      command: up
```
would then have surprising behavior: it would actually update the env under `bbl-state`.

The other possible behavior to get out of this is to overwrite the contents of `bbl-state` if they exist... This might be a bit confusing or problematic under some edge case I'm failing to imagine, but I think it would result in correct behavior and simple configuration-- that example would deploy a second bbl state. The only surprising thing is that if you tried to access non-namey files in that put, but without state_dir set, you'd get the ones from a-second-bbl-state.
