### ISSUE TITLE
Args "lb-cert" and "lb-key" expected as files; Cannot use pipeline variables

### ISSUE THREAD

**Issue by mattysweeps** [cloudfoundry/bbl-state-resource#9]
bbl expects the load balancer arguments to be files. 

It would be great if the bbl-state-resource had logic around these parameters, allowing me to store them as pipeline variables.

```YAML
jobs:
  - name: bbl-up
    plan:
      - put: bbl-state
        params:
          command: up
          name: ((bbl_env_name))
          args:
            lb-cert: ((load_balancer_cert)) # doesn't work b/c it's the PEM content, not a file
            lb-key: ((load_balancer_key)) # doesn't work b/c it's the PEM content, not a file
```
